WIP
heroku/libcnb.rs pull request #492
Opened 2022-08-30 12:06 UTC by Malax

2022-08-30 17:13 UTC, edmorley requested changes
Thank you for doing this! I agree the benefits outweigh the downsides.

Could you also add some docs on releasing (perhaps a "Releasing" section of a `CONTRIBUTING.md` or `MAINTAINERS.md` or similar, based on the checklist in #335) so it's clearer how the new workflow will work? 

eg: One question I had was "are we now only going to create one tag/GitHub release entry?" and these docs would answer that/allow us to discuss/review those changes along with the code changes.

2022-08-30 17:13 UTC, edmorley commented on CHANGELOG.md
> +### Changes
```suggestion
### Changed
```

(To make tense consistent with the other sections, plus the suggested categories from https://keepachangelog.com/en/1.0.0/ )

2022-08-31 08:55 UTC, Malax commented
I added a `RELEASING.md` in [48ff87c](https://github.com/heroku/libcnb.rs/pull/492/commits/48ff87c059674081f8b39ed7520e065f2d9447c0). I didn't go with `MAINTAINERS.md` since prior-art looks like it's most often used for a list of maintainers, not maintainer instructions.

2022-08-31 09:48 UTC, edmorley approved these changes
🎉

2022-08-31 11:59 UTC, merged