Clean up `TestContext` when pack build unexpectedly succeeds
heroku/libcnb.rs pull request #588
Opened 2023-07-05 19:45 UTC by colincasey

Moves the creation of the `TestContext` to before the invocation of `run_pack_command` so that the context will be cleaned up regardless of the outcome.

@fixes #586

2023-07-07 16:40 UTC, schneems requested changes
Your PR looks good in terms of I think it does what it says it does. I'm wanting to make it so that it doesn't regress in the future i.e. if someone were to re-order the commands in a future PR tests wouldn't fail.

That's the "changes requested": To encode the fix in the build/test logic (through tests, types, or both).

## We could (brainstorm):

- Add a test for this explicit behavior (probably hard and/or  expensive)
- Couple `run_pack_command` with needing a `TestContext` (even if it's not used) to force it's creation before it's run or possibly introduce another function
- Move the creation of the TestContext to the same location that allocates the resource (RAII)
- Couple the creation of the image name with the creation of something that tears it down.

Ideally I want to move the logic closest to where the resource is allocated. In this case we decouple creating an image name from allocating/generating that image (via pack). I'm proposing to couple the teardown logic of the image name along with image name creation so then there's never a scenario where one would be created and not torn down.

## Sketch

- Introduce a `ImageName` struct that holds, well, an image name.
- Have `util::random_docker_identifier()` return this new struct instead of a string
- Move the drop logic to this struct `ImageName` struct
- Add a new field to TestContext to hold an ImageName

Now when `TestContext` is dropped it will drop it's contents and call drop on `ImageName` triggering the cleanup (existing behavior is preserved). And since `ImageName` is allocated before `run_pack_command` is ever called, if it fails then `ImageName` drop behavior will be called (new behavior). 

This assumes that the drop logic is a no-op if an image name has not been created in docker.

2023-07-25 09:57 UTC, Malax commented on CHANGELOG.md
> +- `libcnb-test`: ensures that an image created during a test run will be cleaned up when `.expected_pack_result(PackResult::Failure)` is used but the result is  `PackResult::Success`. ([#588](https:/
```suggestion
- `libcnb-test`: ensures that an image created during a test run will be cleaned up when `.expected_pack_result(PackResult::Failure)` is used but the result is `PackResult::Success`. ([#588](https://github.com/heroku/libcnb.rs/pull/588))
```

2023-07-31 09:49 UTC, Malax commented
@edmorley does #619 also resolve this issue? In any case, this PR here won't apply cleanly anymore after `run_pack_command` changed so much.:/

2023-07-31 10:00 UTC, edmorley commented
@Malax No #619 does not fix this directly, though it does give more options here as to how to fix this issue.

It seems the options here now are to:
1. (This is now only possible after #619) Make an explicit call to remove the Docker image on the "successful but panicing" branch here: https://github.com/heroku/libcnb.rs/blob/346a186b35a5941a593228b25d68a196c7e75116/libcnb-test/src/test_runner.rs#L170-L171
2. (As Richard suggested above) Add a new `Image` (or similar) struct, which has the `Drop` on it itself, which can be created sooner than the `TestContext` - and will handle the image removal itself, rather than on `TestContext` drop.
3. Move the creation of `TestContext` earlier (the current PR's implementation), but add a comment explaining why.

I think my preference is for option (1) or (2). 

Thoughts?

2023-08-03 11:13 UTC, Malax commented
> Thoughts?

I would vote for option 1 here. I find `Drop` complicates the code and makes it hard to reason about. If we can avoid using it I think we should.

2023-08-08 08:33 UTC, edmorley commented
> I would vote for option 1 here. I find `Drop` complicates the code and makes it hard to reason about. If we can avoid using it I think we should.

Works for me! I've opened #625.

2023-08-08 08:53 UTC, closed without merging